apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespaces: web
  labels:
    app: nginx
spec:
  replicas: 1  # 設定2個副本
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespaces: web
spec:
  type: NodePort  # 使用 NodePort 讓外部可以存取
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80       # 服務內部的 Port
    targetPort: 80 # Pod 的 Port
    nodePort: 30080 # 設定本機端口 (30000~32767 範圍)
